"""empresa_geolocalizacoes

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-19 02:06:41.603633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa_geolocalizacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('fonte', sa.String(length=40), nullable=False),
    sa.Column('precisao', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('endereco_hash', sa.String(length=64), nullable=True),
    sa.Column('consultado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cep_status', sa.String(length=16), server_default='pendente', nullable=False),
    sa.Column('cep_tentativas', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cep_consultado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cep_erro', sa.Text(), nullable=True),
    sa.CheckConstraint("(status = 'localizada' AND latitude IS NOT NULL AND longitude IS NOT NULL) OR (status <> 'localizada' AND latitude IS NULL AND longitude IS NULL)", name='ck_geo_status_coordenadas'),
    sa.CheckConstraint("cep_status IN ('pendente', 'localizada', 'nao_encontrada', 'ambigua', 'invalida', 'erro')", name='ck_geo_cep_status'),
    sa.CheckConstraint("precisao IN ('municipio', 'cep')", name='ck_geo_precisao'),
    sa.CheckConstraint("status IN ('localizada', 'nao_encontrada', 'ambigua', 'erro')", name='ck_geo_status'),
    sa.CheckConstraint('latitude IS NULL OR (latitude BETWEEN -90 AND 90)', name='ck_geo_latitude'),
    sa.CheckConstraint('longitude IS NULL OR (longitude BETWEEN -180 AND 180)', name='ck_geo_longitude'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empresa_geolocalizacoes')
    # ### end Alembic commands ###
