"""Etapa 7: WhatsApp automatizado (tabelas aditivas)

Revision ID: 0007
Revises: 0006

DDL gerado a partir de api/persistence/whatsapp_models.py e congelado aqui.
Não altera nenhuma tabela existente.
"""
from alembic import op

revision = "0007"
down_revision = "0006"
branch_labels = None
depends_on = None

DDL = [
    'CREATE TABLE commercial_policies (\n\tid SERIAL NOT NULL, \n\tversao INTEGER NOT NULL, \n\tativa BOOLEAN DEFAULT false NOT NULL, \n\tconfig JSONB NOT NULL, \n\tcriado_por VARCHAR(120) NOT NULL, \n\tcriado_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (versao)\n)',
    'CREATE UNIQUE INDEX uq_commercial_policy_ativa ON commercial_policies (ativa) WHERE ativa',
    "CREATE TABLE whatsapp_accounts (\n\tid SERIAL NOT NULL, \n\tnumero VARCHAR(20), \n\testado VARCHAR(30) DEFAULT 'desconectado' NOT NULL, \n\tcomando_pendente VARCHAR(20), \n\tqr_atual TEXT, \n\tautomacao_habilitada BOOLEAN DEFAULT false NOT NULL, \n\tmotivo_pausa TEXT, \n\tkill_geracao INTEGER DEFAULT '0' NOT NULL, \n\theartbeat_em TIMESTAMP WITH TIME ZONE, \n\tgateway_lease_id VARCHAR(64), \n\tgateway_lease_ate TIMESTAMP WITH TIME ZONE, \n\ttimezone VARCHAR(60) DEFAULT 'America/Sao_Paulo' NOT NULL, \n\tlimites JSONB DEFAULT '{}'::jsonb NOT NULL, \n\terros_consecutivos INTEGER DEFAULT '0' NOT NULL, \n\tcriado_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_wa_conta_estado CHECK (estado IN ('desconectado','aguardando_qr','conectando','conectado','reconectando','requer_pareamento','pausado_por_erro'))\n)",
    'CREATE TABLE whatsapp_contacts (\n\tid SERIAL NOT NULL, \n\ttelefone_e164 VARCHAR(20), \n\tnome_exibido VARCHAR(255), \n\tidentidade_resolvida BOOLEAN DEFAULT false NOT NULL, \n\tcriado_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id)\n)',
    'CREATE TABLE whatsapp_audit_events (\n\tid SERIAL NOT NULL, \n\tconta_id INTEGER, \n\tator VARCHAR(60) NOT NULL, \n\tacao VARCHAR(60) NOT NULL, \n\talvo_tipo VARCHAR(30), \n\talvo_id INTEGER, \n\tdetalhes JSONB, \n\tcriado_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(conta_id) REFERENCES whatsapp_accounts (id)\n)',
    "CREATE TABLE whatsapp_auth_state (\n\tconta_id INTEGER NOT NULL, \n\ttipo VARCHAR(60) NOT NULL, \n\titem_id VARCHAR(255) NOT NULL, \n\tconteudo BYTEA NOT NULL, \n\tversao INTEGER DEFAULT '1' NOT NULL, \n\tatualizado_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (conta_id, tipo, item_id), \n\tFOREIGN KEY(conta_id) REFERENCES whatsapp_accounts (id) ON DELETE CASCADE\n)",
    "CREATE TABLE whatsapp_contact_identifiers (\n\tid SERIAL NOT NULL, \n\tconta_id INTEGER NOT NULL, \n\tcontato_id INTEGER NOT NULL, \n\ttipo VARCHAR(10) NOT NULL, \n\tidentificador VARCHAR(255) NOT NULL, \n\torigem VARCHAR(40) NOT NULL, \n\tcriado_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_wa_identificador UNIQUE (conta_id, tipo, identificador), \n\tCONSTRAINT ck_wa_identificador_tipo CHECK (tipo IN ('telefone','jid','lid')), \n\tFOREIGN KEY(conta_id) REFERENCES whatsapp_accounts (id) ON DELETE CASCADE, \n\tFOREIGN KEY(contato_id) REFERENCES whatsapp_contacts (id) ON DELETE CASCADE\n)",
    "CREATE TABLE whatsapp_inbound_events (\n\tid BIGSERIAL NOT NULL, \n\tconta_id INTEGER NOT NULL, \n\ttipo VARCHAR(12) NOT NULL, \n\tprovider_msg_id VARCHAR(120), \n\tfrom_me BOOLEAN DEFAULT false NOT NULL, \n\tjid VARCHAR(255), \n\tjid_alt VARCHAR(255), \n\tpush_name VARCHAR(255), \n\ttipo_msg VARCHAR(20), \n\ttexto TEXT, \n\torigem VARCHAR(20) DEFAULT 'tempo_real' NOT NULL, \n\tts_provedor TIMESTAMP WITH TIME ZONE, \n\tdados JSONB, \n\tprocessado BOOLEAN DEFAULT false NOT NULL, \n\tcriado_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(conta_id) REFERENCES whatsapp_accounts (id)\n)",
    'CREATE INDEX ix_wa_evento_pendente ON whatsapp_inbound_events (processado, id)',
    "CREATE UNIQUE INDEX uq_wa_evento_msg ON whatsapp_inbound_events (conta_id, provider_msg_id, from_me, tipo) WHERE tipo = 'mensagem' AND provider_msg_id IS NOT NULL",
    'CREATE TABLE whatsapp_suppressions (\n\tid SERIAL NOT NULL, \n\tconta_id INTEGER NOT NULL, \n\tcontato_id INTEGER NOT NULL, \n\tmotivo VARCHAR(30) NOT NULL, \n\torigem VARCHAR(60) NOT NULL, \n\tcriado_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_wa_supressao UNIQUE (conta_id, contato_id), \n\tFOREIGN KEY(conta_id) REFERENCES whatsapp_accounts (id), \n\tFOREIGN KEY(contato_id) REFERENCES whatsapp_contacts (id)\n)',
    "CREATE TABLE whatsapp_authorizations (\n\tid SERIAL NOT NULL, \n\tconta_id INTEGER NOT NULL, \n\tcontato_id INTEGER NOT NULL, \n\tempresa_id INTEGER, \n\tautorizado_por VARCHAR(120) NOT NULL, \n\ttelefone_exato VARCHAR(20) NOT NULL, \n\tstatus VARCHAR(12) DEFAULT 'ativa' NOT NULL, \n\tversao INTEGER DEFAULT '1' NOT NULL, \n\tpolitica_versao INTEGER NOT NULL, \n\texpira_em TIMESTAMP WITH TIME ZONE, \n\trevogado_em TIMESTAMP WITH TIME ZONE, \n\tmotivo_revogacao TEXT, \n\tcriado_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_wa_autorizacao_status CHECK (status IN ('ativa','revogada','expirada')), \n\tFOREIGN KEY(conta_id) REFERENCES whatsapp_accounts (id), \n\tFOREIGN KEY(contato_id) REFERENCES whatsapp_contacts (id), \n\tFOREIGN KEY(empresa_id) REFERENCES empresas (id)\n)",
    "CREATE UNIQUE INDEX uq_wa_autorizacao_ativa ON whatsapp_authorizations (conta_id, contato_id) WHERE status = 'ativa'",
    "CREATE TABLE whatsapp_conversations (\n\tid SERIAL NOT NULL, \n\tconta_id INTEGER NOT NULL, \n\tcontato_id INTEGER NOT NULL, \n\tempresa_id INTEGER, \n\tautorizacao_id INTEGER, \n\tcontrole VARCHAR(20) DEFAULT 'fora_escopo' NOT NULL, \n\testagio VARCHAR(20) DEFAULT 'abordagem' NOT NULL, \n\tmotivo_escalada TEXT, \n\tultima_recebida_em TIMESTAMP WITH TIME ZONE, \n\tultima_enviada_em TIMESTAMP WITH TIME ZONE, \n\tversao INTEGER DEFAULT '1' NOT NULL, \n\tresumo TEXT, \n\tresumo_ate_msg_id INTEGER, \n\testado_comercial JSONB DEFAULT '{}'::jsonb NOT NULL, \n\tcriado_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_wa_conversa_contato UNIQUE (conta_id, contato_id), \n\tCONSTRAINT ck_wa_conversa_controle CHECK (controle IN ('automatizada','humano','pausada','encerrada','fora_escopo')), \n\tCONSTRAINT ck_wa_conversa_estagio CHECK (estagio IN ('abordagem','qualificacao','proposta','negociacao','aceita','perdida')), \n\tFOREIGN KEY(conta_id) REFERENCES whatsapp_accounts (id), \n\tFOREIGN KEY(contato_id) REFERENCES whatsapp_contacts (id), \n\tFOREIGN KEY(empresa_id) REFERENCES empresas (id), \n\tFOREIGN KEY(autorizacao_id) REFERENCES whatsapp_authorizations (id)\n)",
    'CREATE TABLE commercial_demands (\n\tid SERIAL NOT NULL, \n\tconversa_id INTEGER NOT NULL, \n\tdescricao TEXT NOT NULL, \n\trevisada BOOLEAN DEFAULT false NOT NULL, \n\tcriado_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(conversa_id) REFERENCES whatsapp_conversations (id)\n)',
    "CREATE TABLE commercial_proposals (\n\tid SERIAL NOT NULL, \n\tconversa_id INTEGER NOT NULL, \n\tpolitica_versao INTEGER NOT NULL, \n\tpacote VARCHAR(10) NOT NULL, \n\titens JSONB NOT NULL, \n\tsetup_centavos INTEGER NOT NULL, \n\tmensalidade_centavos INTEGER DEFAULT '0' NOT NULL, \n\tdesconto_pct INTEGER DEFAULT '0' NOT NULL, \n\tstatus VARCHAR(12) DEFAULT 'enviada' NOT NULL, \n\tcriado_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(conversa_id) REFERENCES whatsapp_conversations (id)\n)",
    "CREATE TABLE whatsapp_jobs (\n\tid SERIAL NOT NULL, \n\ttipo VARCHAR(20) NOT NULL, \n\tconta_id INTEGER NOT NULL, \n\tconversa_id INTEGER NOT NULL, \n\tchave_idempotencia VARCHAR(120) NOT NULL, \n\tstatus VARCHAR(15) DEFAULT 'pendente' NOT NULL, \n\ttentativas INTEGER DEFAULT '0' NOT NULL, \n\tproxima_execucao_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tprimeira_entrada_em TIMESTAMP WITH TIME ZONE, \n\tlease_ate TIMESTAMP WITH TIME ZONE, \n\terro TEXT, \n\tcriado_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_wa_job_status CHECK (status IN ('pendente','em_execucao','concluido','falhou','cancelado')), \n\tFOREIGN KEY(conta_id) REFERENCES whatsapp_accounts (id), \n\tFOREIGN KEY(conversa_id) REFERENCES whatsapp_conversations (id), \n\tUNIQUE (chave_idempotencia)\n)",
    'CREATE INDEX ix_wa_job_pronto ON whatsapp_jobs (status, proxima_execucao_em)',
    "CREATE TABLE whatsapp_messages (\n\tid SERIAL NOT NULL, \n\tconta_id INTEGER NOT NULL, \n\tconversa_id INTEGER NOT NULL, \n\tcontato_id INTEGER NOT NULL, \n\tdirecao VARCHAR(8) NOT NULL, \n\tautoria VARCHAR(10) NOT NULL, \n\ttipo VARCHAR(20) DEFAULT 'texto' NOT NULL, \n\ttexto TEXT, \n\tprovider_msg_id VARCHAR(120), \n\tprovider_from_me BOOLEAN DEFAULT false NOT NULL, \n\tprovider_jid VARCHAR(255), \n\trespondida_id INTEGER, \n\tts_provedor TIMESTAMP WITH TIME ZONE, \n\trecebida_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\testado_transporte VARCHAR(20) DEFAULT 'entregue' NOT NULL, \n\torigem VARCHAR(20) DEFAULT 'tempo_real' NOT NULL, \n\toutbox_id INTEGER, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_wa_msg_direcao CHECK (direcao IN ('entrada','saida')), \n\tCONSTRAINT ck_wa_msg_autoria CHECK (autoria IN ('cliente','ia','operador')), \n\tFOREIGN KEY(conta_id) REFERENCES whatsapp_accounts (id), \n\tFOREIGN KEY(conversa_id) REFERENCES whatsapp_conversations (id), \n\tFOREIGN KEY(contato_id) REFERENCES whatsapp_contacts (id), \n\tFOREIGN KEY(respondida_id) REFERENCES whatsapp_messages (id)\n)",
    'CREATE UNIQUE INDEX uq_wa_mensagem_provider ON whatsapp_messages (conta_id, provider_msg_id, provider_from_me) WHERE provider_msg_id IS NOT NULL',
    "CREATE TABLE whatsapp_outbox (\n\tid SERIAL NOT NULL, \n\tconta_id INTEGER NOT NULL, \n\tconversa_id INTEGER NOT NULL, \n\tcontato_id INTEGER NOT NULL, \n\tautoria VARCHAR(10) NOT NULL, \n\ttexto TEXT NOT NULL, \n\tstatus VARCHAR(20) DEFAULT 'aguardando_envio' NOT NULL, \n\tprimeiro_contato BOOLEAN DEFAULT false NOT NULL, \n\tmensagem_de_transicao BOOLEAN DEFAULT false NOT NULL, \n\tversao_autorizacao INTEGER, \n\tversao_politica INTEGER, \n\tversao_conversa INTEGER, \n\tkill_geracao INTEGER DEFAULT '0' NOT NULL, \n\tagendado_para TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\ttentativas INTEGER DEFAULT '0' NOT NULL, \n\tlease_ate TIMESTAMP WITH TIME ZONE, \n\tprovider_msg_id VARCHAR(120), \n\tmensagem_id INTEGER, \n\terro TEXT, \n\tcriado_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tenviado_em TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_wa_outbox_status CHECK (status IN ('aguardando_envio','envio_em_andamento','aceita','entregue','lida','falhou','incerto','cancelado')), \n\tFOREIGN KEY(conta_id) REFERENCES whatsapp_accounts (id), \n\tFOREIGN KEY(conversa_id) REFERENCES whatsapp_conversations (id), \n\tFOREIGN KEY(contato_id) REFERENCES whatsapp_contacts (id)\n)",
    'CREATE INDEX ix_wa_outbox_pronta ON whatsapp_outbox (status, agendado_para)',
    'CREATE TABLE commercial_acceptances (\n\tid SERIAL NOT NULL, \n\tproposta_id INTEGER NOT NULL, \n\tmensagem_id INTEGER, \n\tcriado_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (proposta_id), \n\tFOREIGN KEY(proposta_id) REFERENCES commercial_proposals (id), \n\tFOREIGN KEY(mensagem_id) REFERENCES whatsapp_messages (id)\n)',
    'CREATE TABLE whatsapp_ai_runs (\n\tid SERIAL NOT NULL, \n\tconversa_id INTEGER NOT NULL, \n\tjob_id INTEGER, \n\tmodelo VARCHAR(60), \n\tprompt_versao VARCHAR(30), \n\tpolitica_versao INTEGER, \n\ttokens_entrada INTEGER, \n\ttokens_saida INTEGER, \n\tlatencia_ms INTEGER, \n\tdecisao JSONB, \n\tvalidacao VARCHAR(12), \n\terro TEXT, \n\tcriado_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(conversa_id) REFERENCES whatsapp_conversations (id), \n\tFOREIGN KEY(job_id) REFERENCES whatsapp_jobs (id)\n)',
    'CREATE TABLE whatsapp_message_events (\n\tid SERIAL NOT NULL, \n\tmensagem_id INTEGER NOT NULL, \n\tevento VARCHAR(20) NOT NULL, \n\tocorrido_em TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tmetadados JSONB, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(mensagem_id) REFERENCES whatsapp_messages (id) ON DELETE CASCADE\n)',
]


def upgrade() -> None:
    for comando in DDL:
        op.execute(comando)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS whatsapp_message_events, whatsapp_ai_runs, commercial_acceptances, whatsapp_outbox, whatsapp_messages, whatsapp_jobs, commercial_proposals, commercial_demands, whatsapp_conversations, whatsapp_authorizations, whatsapp_suppressions, whatsapp_inbound_events, whatsapp_contact_identifiers, whatsapp_auth_state, whatsapp_audit_events, whatsapp_contacts, whatsapp_accounts, commercial_policies CASCADE")
